sudo: false

language: python

https://docs.travis-ci.com/user/languages/python/#using-tox-as-the-build-script
matrix:
  include:
    - python: 3.8
    - python: 3.7
    - python: 3.6

install: pip install tox-travis

script: tox

deploy:
  provider: pypi
  user: adamhooper
  on:
    tags: true
  skip_existing: true
