sudo: false

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install black pyflakes isort
  - pip install -e .
  - pip freeze

script:
  - pyflakes .
  - black --check .
  - isort --check-only --diff --recursive channels_rabbitmq tests
  - tox

deploy:
  provider: pypi
  user: adamhooper
  on:
    tags: true
  skip_existing: true
